# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{inputs, ...}: {
  flake-file.inputs.nixos-hardware.url = "github:NixOS/nixos-hardware/master";

  den.aspects.fw-laptop = {
    nixos = {
      config,
      lib,
      pkgs,
      modulesPath,
      ...
    }: {
      imports = [
        (modulesPath + "/installer/scan/not-detected.nix")
        inputs.nixos-hardware.nixosModules.framework-13-7040-amd
      ];

      boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod"];
      boot.initrd.kernelModules = [];
      boot.kernelModules = ["kvm-amd"];
      boot.extraModulePackages = [];

      fileSystems."/" = {
        device = "/dev/mapper/luks-cdafa358-f2e9-4509-92f0-9b668ce763f0";
        fsType = "ext4";
      };

      boot.initrd.luks.devices."luks-cdafa358-f2e9-4509-92f0-9b668ce763f0".device = "/dev/disk/by-uuid/cdafa358-f2e9-4509-92f0-9b668ce763f0";

      fileSystems."/boot" = {
        device = "/dev/disk/by-uuid/B6B4-546B";
        fsType = "vfat";
        options = ["fmask=0077" "dmask=0077"];
      };

      swapDevices = [];

      nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
      hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
      hardware.framework.amd-7040.preventWakeOnAC = true;
      hardware.framework.laptop13.audioEnhancement.enable = true;
    };
  };
}
