# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/07244875-f313-49cd-b33c-4a28db389f5d";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/07244875-f313-49cd-b33c-4a28db389f5d";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/07244875-f313-49cd-b33c-4a28db389f5d";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/tmp" =
    { device = "/dev/disk/by-uuid/07244875-f313-49cd-b33c-4a28db389f5d";
      fsType = "btrfs";
      options = [ "subvol=@tmp" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/07244875-f313-49cd-b33c-4a28db389f5d";
      fsType = "btrfs";
      options = [ "subvol=@var_log" ];
    };

  fileSystems."/var/cache" =
    { device = "/dev/disk/by-uuid/07244875-f313-49cd-b33c-4a28db389f5d";
      fsType = "btrfs";
      options = [ "subvol=@var_cache" ];
    };

  fileSystems."/var/tmp" =
    { device = "/dev/disk/by-uuid/07244875-f313-49cd-b33c-4a28db389f5d";
      fsType = "btrfs";
      options = [ "subvol=@var_tmp" ];
    };

  fileSystems."/.snapshots" =
    { device = "/dev/disk/by-uuid/07244875-f313-49cd-b33c-4a28db389f5d";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/C103-0837";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/6e1404b2-bb8f-46aa-8427-5bc6f71def11"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
