{pkgs, ...}: {
  home.packages = with pkgs; [
    anki
    ansible
    bitwarden
    bitwarden-cli
    brightnessctl
    evince
    ffmpeg
    gcr
    hunspell
    hunspellDicts.en_AU-large
    hunspellDicts.fr-any
    hunspellDicts.th_TH
    imagemagick
    jellyfin-mpv-shim
    loupe
    mpv
    mqtt-explorer
    nautilus
    nwg-look
    obsidian
    opentofu
    protonvpn-gui
    signal-desktop-bin
    sqlite
    sshpass
    sushi
    terraform
    trezor-suite
    ventoy
    winbox4
    youtube-music
  ];
}
