{
  pkgs,
  inputs,
  ...
}: {
  environment.systemPackages = with pkgs; [
    bitwarden-desktop
    brightnessctl
    cifs-utils
    dig
    duf
    eza
    ffmpeg
    fw-ectool
    gnomeExtensions.solaar-extension
    jellyfin-mpv-shim
    killall
    mpv
    nvme-cli
    playerctl
    ripgrep
    rose-pine-cursor
    inputs.rose-pine-hyprcursor.packages.${pkgs.system}.default
    tree
    unrar
    unzip
    vivid
    wget
    zoxide
  ];
}
